### PR TITLE
Migrate from npm to yarn

### PR DESCRIPTION
**Pull request by imbsky**

### CODE REVIEW

**Comment by avsm** [comment]
Why?

**Comment by imbsky** [comment]
Yarn is said to be basically faster, and it has better interface. For example, there is no `yarn upgrade-interactive --latest` like command in npm.

**Comment by imbsky** [comment]
Also, for npm, the npm and npx commands are sometimes confusing. But it's often a matter of taste. Note: vscode-ocaml-platform uses yarn.

**Comment by avsm** [comment]
Looks fine, but needs a rebase against `master` to merge.

**Comment by imbsky** [comment]
Done

**Comment by avsm** [comment]
thanks!

**Pull request merged**
